--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15
-- Dumped by pg_dump version 14.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    state_province character varying(100),
    country character varying(50) NOT NULL,
    postal_code character varying(10) NOT NULL,
    city character varying(100) NOT NULL,
    type_address_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."address type" (
    id bigint NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public."address type" OWNER TO postgres;

--
-- Name: address type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."address type" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."address type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    birth_date date NOT NULL,
    start_date date NOT NULL,
    photo character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    job_title_id bigint NOT NULL
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- Name: employee_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.employee_customuser OWNER TO postgres;

--
-- Name: employee_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.employee_customuser_groups OWNER TO postgres;

--
-- Name: employee_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.employee_customuser_user_permissions OWNER TO postgres;

--
-- Name: employee_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_title_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_title_type (
    id bigint NOT NULL,
    description character varying(30) NOT NULL
);


ALTER TABLE public.job_title_type OWNER TO postgres;

--
-- Name: job_title_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_title_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_title_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.address (id, state_province, country, postal_code, city, type_address_id, employee_id) FROM stdin;
\.


--
-- Data for Name: address type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."address type" (id, description) FROM stdin;
1	Home: Primary residence
2	Office: Business location
3	School: Educational institution
4	Park: Public recreational area
5	Mailbox: Private mailbox
6	University: Higher education institution
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	admin
2	employee
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add address type	6	add_addresstype
22	Can change address type	6	change_addresstype
23	Can delete address type	6	delete_addresstype
24	Can view address type	6	view_addresstype
25	Can add job title type	7	add_jobtitletype
26	Can change job title type	7	change_jobtitletype
27	Can delete job title type	7	delete_jobtitletype
28	Can view job title type	7	view_jobtitletype
29	Can add user	8	add_customuser
30	Can change user	8	change_customuser
31	Can delete user	8	delete_customuser
32	Can view user	8	view_customuser
33	Can add employee	9	add_employee
34	Can change employee	9	change_employee
35	Can delete employee	9	delete_employee
36	Can view employee	9	view_employee
37	Can add address	10	add_address
38	Can change address	10	change_address
39	Can delete address	10	delete_address
40	Can view address	10	view_address
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-02-13 03:38:19.864909+00	1	Software Developer	1	[{"added": {}}]	7	1
2	2025-02-13 03:38:33.224469+00	2	Data Engineer	1	[{"added": {}}]	7	1
3	2025-02-13 03:38:45.486044+00	3	Systems Analyst	1	[{"added": {}}]	7	1
4	2025-02-13 03:38:56.768478+00	4	Cybersecurity Specialist	1	[{"added": {}}]	7	1
5	2025-02-13 03:39:12.593394+00	5	Network Administrator	1	[{"added": {}}]	7	1
6	2025-02-13 03:39:59.30302+00	1	Home: Primary residence	1	[{"added": {}}]	6	1
7	2025-02-13 03:40:11.409813+00	2	Office: Business location	1	[{"added": {}}]	6	1
8	2025-02-13 03:40:21.103644+00	3	School: Educational institution	1	[{"added": {}}]	6	1
9	2025-02-13 03:40:46.661913+00	4	Park: Public recreational area	1	[{"added": {}}]	6	1
10	2025-02-13 03:40:54.399882+00	5	Mailbox: Private mailbox	1	[{"added": {}}]	6	1
11	2025-02-13 03:41:12.293543+00	6	University: Higher education institution	1	[{"added": {}}]	6	1
12	2025-02-13 03:41:34.504151+00	1	admin	1	[{"added": {}}]	3	1
13	2025-02-13 03:41:43.548228+00	2	employee	1	[{"added": {}}]	3	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	employee	addresstype
7	employee	jobtitletype
8	employee	customuser
9	employee	employee
10	employee	address
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-02-13 03:31:14.877549+00
2	contenttypes	0002_remove_content_type_name	2025-02-13 03:31:14.884808+00
3	auth	0001_initial	2025-02-13 03:31:14.93042+00
4	auth	0002_alter_permission_name_max_length	2025-02-13 03:31:14.935147+00
5	auth	0003_alter_user_email_max_length	2025-02-13 03:31:14.942758+00
6	auth	0004_alter_user_username_opts	2025-02-13 03:31:14.948419+00
7	auth	0005_alter_user_last_login_null	2025-02-13 03:31:14.953984+00
8	auth	0006_require_contenttypes_0002	2025-02-13 03:31:14.956528+00
9	auth	0007_alter_validators_add_error_messages	2025-02-13 03:31:14.960639+00
10	auth	0008_alter_user_username_max_length	2025-02-13 03:31:14.966063+00
11	auth	0009_alter_user_last_name_max_length	2025-02-13 03:31:14.971906+00
12	auth	0010_alter_group_name_max_length	2025-02-13 03:31:14.978855+00
13	auth	0011_update_proxy_permissions	2025-02-13 03:31:14.984378+00
14	auth	0012_alter_user_first_name_max_length	2025-02-13 03:31:14.988848+00
15	employee	0001_initial	2025-02-13 03:31:15.091248+00
16	admin	0001_initial	2025-02-13 03:31:15.119722+00
17	admin	0002_logentry_remove_auto_add	2025-02-13 03:31:15.126157+00
18	admin	0003_logentry_add_action_flag_choices	2025-02-13 03:31:15.132276+00
19	sessions	0001_initial	2025-02-13 03:31:15.148271+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
dbyhehlduno1348w8qhz34udbb3625rj	.eJxVjDsOwjAQBe_iGln-ZONASc8ZrN31ggPIluKkQtwdLKWA9s3Me6mI25rj1mSJc1InZdXhdyPkh5QO0h3LrWquZV1m0l3RO236UpM8z7v7d5Cx5W8NxgQLgQVoFHDoHNmJGLzAEDjQOGBy0pFDtkDBWCLwaYKr8e4o6v0B0UU3iQ:1tiQ27:z8Eih-4SmgfI0pxPrNISc3xDbKQgs_EERiu2RWJFM3g	2025-02-27 03:36:59.142595+00
\.


--
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (id, first_name, last_name, birth_date, start_date, photo, user_id, job_title_id) FROM stdin;
\.


--
-- Data for Name: employee_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$870000$PEhYeXVOhAGsd4P3BmFK1x$DrTsYJvponIKQ4Q2CI/4NgZ5FNqKqb23NnQjCWMIO4c=	2025-02-13 03:36:59.139414+00	t	admin			admin@gmail.com	t	t	2025-02-13 03:36:31.937452+00
\.


--
-- Data for Name: employee_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: employee_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: job_title_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_title_type (id, description) FROM stdin;
1	Software Developer
2	Data Engineer
3	Systems Analyst
4	Cybersecurity Specialist
5	Network Administrator
\.


--
-- Name: address type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."address type_id_seq"', 6, true);


--
-- Name: address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.address_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 13, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: employee_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_customuser_groups_id_seq', 1, false);


--
-- Name: employee_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_customuser_id_seq', 1, true);


--
-- Name: employee_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_customuser_user_permissions_id_seq', 1, false);


--
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_id_seq', 1, false);


--
-- Name: job_title_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_title_type_id_seq', 5, true);


--
-- Name: address type address type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."address type"
    ADD CONSTRAINT "address type_pkey" PRIMARY KEY (id);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: employee_customuser_groups employee_customuser_groups_customuser_id_group_id_aaf7df17_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_groups
    ADD CONSTRAINT employee_customuser_groups_customuser_id_group_id_aaf7df17_uniq UNIQUE (customuser_id, group_id);


--
-- Name: employee_customuser_groups employee_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_groups
    ADD CONSTRAINT employee_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: employee_customuser employee_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser
    ADD CONSTRAINT employee_customuser_pkey PRIMARY KEY (id);


--
-- Name: employee_customuser_user_permissions employee_customuser_user_customuser_id_permission_387e0f79_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_user_permissions
    ADD CONSTRAINT employee_customuser_user_customuser_id_permission_387e0f79_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: employee_customuser_user_permissions employee_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_user_permissions
    ADD CONSTRAINT employee_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: employee_customuser employee_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser
    ADD CONSTRAINT employee_customuser_username_key UNIQUE (username);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- Name: job_title_type job_title_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_title_type
    ADD CONSTRAINT job_title_type_pkey PRIMARY KEY (id);


--
-- Name: address_employee_id_36e4dc0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_employee_id_36e4dc0e ON public.address USING btree (employee_id);


--
-- Name: address_type_address_id_8f112b66; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_type_address_id_8f112b66 ON public.address USING btree (type_address_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: employee_customuser_groups_customuser_id_2d7938a7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_customuser_groups_customuser_id_2d7938a7 ON public.employee_customuser_groups USING btree (customuser_id);


--
-- Name: employee_customuser_groups_group_id_31af61bb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_customuser_groups_group_id_31af61bb ON public.employee_customuser_groups USING btree (group_id);


--
-- Name: employee_customuser_user_permissions_customuser_id_a6a6b2a1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_customuser_user_permissions_customuser_id_a6a6b2a1 ON public.employee_customuser_user_permissions USING btree (customuser_id);


--
-- Name: employee_customuser_user_permissions_permission_id_77d88afa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_customuser_user_permissions_permission_id_77d88afa ON public.employee_customuser_user_permissions USING btree (permission_id);


--
-- Name: employee_customuser_username_177b7b2a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_customuser_username_177b7b2a_like ON public.employee_customuser USING btree (username varchar_pattern_ops);


--
-- Name: employee_job_title_id_a8f5a4cb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_job_title_id_a8f5a4cb ON public.employee USING btree (job_title_id);


--
-- Name: employee_user_id_cc4f5a1c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employee_user_id_cc4f5a1c ON public.employee USING btree (user_id);


--
-- Name: address address_employee_id_36e4dc0e_fk_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_employee_id_36e4dc0e_fk_employee_id FOREIGN KEY (employee_id) REFERENCES public.employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: address address_type_address_id_8f112b66_fk_address type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT "address_type_address_id_8f112b66_fk_address type_id" FOREIGN KEY (type_address_id) REFERENCES public."address type"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_employee_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_employee_customuser_id FOREIGN KEY (user_id) REFERENCES public.employee_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_customuser_groups employee_customuser__customuser_id_2d7938a7_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_groups
    ADD CONSTRAINT employee_customuser__customuser_id_2d7938a7_fk_employee_ FOREIGN KEY (customuser_id) REFERENCES public.employee_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_customuser_user_permissions employee_customuser__customuser_id_a6a6b2a1_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_user_permissions
    ADD CONSTRAINT employee_customuser__customuser_id_a6a6b2a1_fk_employee_ FOREIGN KEY (customuser_id) REFERENCES public.employee_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_customuser_user_permissions employee_customuser__permission_id_77d88afa_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_user_permissions
    ADD CONSTRAINT employee_customuser__permission_id_77d88afa_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee_customuser_groups employee_customuser_groups_group_id_31af61bb_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_customuser_groups
    ADD CONSTRAINT employee_customuser_groups_group_id_31af61bb_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee employee_job_title_id_a8f5a4cb_fk_job_title_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_job_title_id_a8f5a4cb_fk_job_title_type_id FOREIGN KEY (job_title_id) REFERENCES public.job_title_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: employee employee_user_id_cc4f5a1c_fk_employee_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_user_id_cc4f5a1c_fk_employee_customuser_id FOREIGN KEY (user_id) REFERENCES public.employee_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

