[project]
name = "djrfw-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.6",
    "django-extensions>=3.2.3",
    "djangorestframework>=3.15.2",
    "pillow>=11.1.0",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "faker>=36.1.0",
    "ipdb>=0.13.13",
    "ipython>=8.32.0",
    "isort>=6.0.0",
    "ruff>=0.9.6",
]
